repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        language: system
        entry: cargo fmt --all -- --check
        types: [file, rust]
      - id: check
        name: check
        language: system
        files: '[.]rs$'
        entry: cargo clippy --all-targets
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-merge-conflict
    - id: check-symlinks
    - id: flake8
      exclude: scripts/
      args: ["--config", "python/setup.cfg"]

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
