name: test rust and python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-16.04]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Test with cargo
      uses: actions-rs/cargo@v1.0.1
      with:
          command: test
          toolchain: nightly

    - name: Install dependencies with pip
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: build python package
      working-directory: python
      run: poetry run maturin develop

    - name: Test with pytest
      working-directory: python
      run: poetry run pytest tests

    - name: Release build
      working-directory: python
      run: |
        poetry run maturin build --release --no-sdist -i python

    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/python/')

    - name: Publish test-pypi package 
      working-directory: python
      run: |
        poetry run twine upload --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TEST_PYPI_USER }} -p ${{ secrets.TEST_PYPI_PASS }} target/wheels/*

    - name: Recreate python env and check test-pypi package
      working-directory: python
      run: |
        poetry env remove python
        poetry install
        poetry run pip install --extra-index-url https://testpypi.python.org/pypi pytokenizations
        poetry run pytest tests

    - name: Publish pypi package
      working-directory: python
      run: |
        poetry run twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }} target/wheels/*

