name: test rust and python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo foo

  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/python/')
    needs: test
    runs-on: ubuntu-latst
    steps:
    - run: echo bar